book_magazine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .yasg import urlpatterns as doc_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),  # подключаем urls приложения library
    path('cart/', include('cart.urls')),
]

urlpatterns += doc_urls

handler400 = 'library.views.custom_bad_request_view'
handler403 = 'library.views.custom_permission_denied_view'
handler404 = 'library.views.custom_page_not_found_view'
handler500 = 'library.views.custom_error_view'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', cart_info, name='list_cart'),  # корзина
    path('add/<int:book_id>', cart_add, name='add_cart'),  # добавление книги в корзину
    path('remove/<int:book_id>', cart_remove, name='remove_cart'),  # удаление книги из корзины
    path('clear/', cart_clear, name='clear_cart'),  # очистка корзины

    path('ordering/', create_order, name='ordering'),  # оформление заказа
]

library/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', index, name='home'),  # домашняя страница

    # Книги
    path('books/', BooksList.as_view(), name='books_list'),  # Каталог книг
    path('books/<int:book_id>/', DetailBookView.as_view(), name='detail_books'),  # Подробная информация о книге
    path('genre/<int:genre_id>/', BooksByGenre.as_view(), name='genre'),  # Вывод списка книг по жанрам
    path('books/add_book/', BookCreate.as_view(), name='add_book'),  # Добавление новой книги
    path('books/edit/<int:pk>/', BookUpdate.as_view(), name='edit_book'),  # Редактирование записи о книги
    path('books/delete/<int:pk>/', BookDelete.as_view(), name='delete_book'),  # Удаление книги

    # Поиск книг по сайту
    path('search/', Search.as_view(), name='search'),  # Поиск

    # Аутентификация пользователя
    path('login/', user_login, name='user_login'),  # Авторизация
    path('logout/', user_logout, name='user_logout'),  # Логаут
    path('register/', user_register, name='user_register'),  # Регистрация
    # Обратная связб с магазином
    path('contact/', feedback, name='feedback'),  # Обратная связь

    # Авторы книг
    path('authors/', AuthorsList.as_view(), name='authors_list'),  # Список авторов
    path('authors/<int:author_id>/', DetailAuthorView.as_view(), name='detail_author'),
    # Подробная информация об авторе
    path('authors/add_author/', AuthorCreate.as_view(), name='add_author'),  # Добавление нового автора
    path('authors/edit/<int:pk>/', AuthorUpdate.as_view(), name='edit_author'),  # Редактирование записи об авторе
    path('authors/delete/<int:pk>/', AuthorDelete.as_view(), name='delete_author'),  # Удаление автора

    # Служебные страницы для работников магазина
    path('employee/', EmployeeView.as_view(), name='employee'),  # Служебная страница
    path('employee/book_list/', EmployeeBooksList.as_view(), name='employee_book_list'),  # Список книг для работников
    path('employee/author_list/', EmployeeAuthorList.as_view(), name='employee_author_list'),
    # Список авторов для работников

    # Маршруты для просмотра кастомных ошибок
    path('errors/403/', permission_denied_view),  # В доступе отказано
    path('errors/404/', page_not_found_view),  # Страница не найдена
    path('errors/400/', bad_request_view),  # Неверный запрос
    path('errors/500/', server_error_view),  # Ошибка сервера

    # API
    path('api/v1/auth/', include('rest_framework.urls')),  # подключение маршрута авторизации

    # Книги
    path('api/v1/books/', BookAPIListView.as_view(), name='api_books_list'),  # Вывод списка книг
    path('api/v1/books/<int:pk>/', BookAPIDetailView.as_view(), name='api_book_detail'),  # Подробная информация о книге
    path('api/v1/books/create/', BookAPICreateView.as_view(), name='api_book_create'),  # Создание новой книги
    path('api/v1/books/update/<int:pk>/', BookAPIUpdateView.as_view(), name='api_book_update'),  # Изменение записи о книге
    path('api/v1/books/delete/<int:pk>/', BookAPIDeleteView.as_view()),  # Удаление книги

    # Авторы
    path('api/v1/authors/', AuthorAPIListView.as_view()),  # Список авторов
    path('api/v1/authors/<int:pk>/', AuthorAPIDetailView.as_view()),  # Подробная информация об авторе
    path('api/v1/authors/create/', AuthorAPICreateView.as_view()),  # Создание нового автора
    path('api/v1/authors/update/<int:pk>/', AuthorAPIUpdateView.as_view()),  # Изменение сущетвующего автора
    path('api/v1/authors/delete/<int:pk>/', AuthorAPIDeleteView.as_view()),  # Удаление автора

    # Жанры
    path('api/v1/genres/', GenresAPIListView.as_view()),
    path('api/v1/genres/create/', GenresAPICreateView.as_view()),  # Создание нового жанра
    path('api/v1/genres/update/<int:pk>/', GenresAPIUpdateView.as_view()),  # Изменение сущетвующего жанра
    path('api/v1/genres/delete/<int:pk>/', GenresAPIDeleteView.as_view()),  # Удаление жанра

    # Отзывы к книгам
    path('api/v1/reviews/', ReviewsAPICreateView.as_view()),  # Создание отзыва к книге
    path('api/v1/reviews/delete/<int:pk>/', ReviewsAPIDeleteView.as_view()),  # Удаление отзыва о книге
]

library/models.py
import datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
# создадим модель Жанров книг
class Genre(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название жанра')

    # отобразим информацию об объекте класса в админке
    def __str__(self):
        return self.title

    # настраиваем отображение приложения в админке
    class Meta:
        verbose_name = 'Жанр книги'
        verbose_name_plural = 'Жанры книг'
        ordering = ['title']  # сортировка в админке

    # определяем метод, которым выстраиваем ссылку для получения книг по жанру
    def get_absolute_url(self):
        return reverse('genre', kwargs={'genre_id': self.pk})


# определяем выбор значений для поля cover_type
COVER_CHOISES = (
    ('мягкая', 'мягкая'),
    ('твердая', 'твердая')
)
# определяем выбор значений для поля pub_date
YEAR_CHOICES = [(y, y) for y in range(1800, datetime.date.today().year + 1)]


# создаем модель Книг
class Book(models.Model):
    # поле обязательно для заполнения и ставим ограничение в 255 символов
    title = models.CharField(max_length=250, verbose_name='Название книги')
    # поле описания, к заполнению необязательно
    description = models.TextField(null=True, blank=True, verbose_name='Описание книги')
    # т.к. Integer слишком большое поле и может хранить в себе отрицательные значения
    # нам достаточно Decimal, поставим ограничение на количество знаков, и уберем цифры после запятой
    num_pages = models.DecimalField(max_digits=4, decimal_places=0, verbose_name='Количество страниц')
    # поле выбора обложки, вынесем выбор значений в отдельный список
    cover_type = models.CharField(max_length=7, choices=COVER_CHOISES, default='твердая', verbose_name='Тип обложки')
    # поле цены книги, особых требований к нему нет
    price = models.FloatField(verbose_name='Цена')
    # в поле размера книги поставим ограничение на количество символов и  сделаем необязательным к заполнению
    sizes = models.CharField(max_length=50, null=True, blank=True, verbose_name='Размер книги/формат издания')
    # поскольку в дате публикации указывается только год, сделаем поле Integer с выбором значений,
    # по умолчанию установим текущий год
    pub_date = models.IntegerField(choices=YEAR_CHOICES,
                                   default=datetime.datetime.now().year, verbose_name='Год издания')

    # добавим поля для обложки книги, укажем допустимый тип загружаемых файлов
    photo_cover = models.ImageField(upload_to='image/%Y/%m/%d',
                                    validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])],
                                    null=True, blank=True, verbose_name='Передняя обложка')
    photo_back = models.ImageField(upload_to='image/%Y/%m/%d',
                                   validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])],
                                   null=True, blank=True, verbose_name='Задняя обложка')
    genres = models.ManyToManyField(Genre, verbose_name='Жанр книги')
    owner = models.ForeignKey('Author', on_delete=models.SET_NULL, verbose_name='Автор книги', null=True, blank=True)

    # отобразим информацию об объекте класса в админке
    def __str__(self):
        return self.title

    # настраиваем отображение приложения в админке
    class Meta:
        verbose_name = 'Книги'
        verbose_name_plural = 'Каталог книг'
        ordering = ['title']  # сортировка в админке

    # определяем метод, которым выстраиваем ссылку для подробного описания книги и передаем ее в шаблон
    def get_absolute_url(self):
        return reverse('detail_books', kwargs={'book_id': self.pk})


RAITING_CHOICES = [(y, y) for y in range(1, 6)]


# модель Отзывов
class Reviews(models.Model):
    book_connected = models.ForeignKey(Book, related_name='reviews', on_delete=models.CASCADE, verbose_name='Книга')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор отзыва')
    content = models.TextField(verbose_name='Отзыв')
    raiting = models.IntegerField(choices=RAITING_CHOICES,
                                  default=5, verbose_name='Рейтинг книги')
    date_posted = models.DateTimeField(default=timezone.now, verbose_name='Дата размещения отзыва')

    def __str__(self):
        return str(self.author) + ', ' + self.book_connected.title[:40]

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


# модель Автор
class Author(models.Model):
    full_name = models.CharField(max_length=250, verbose_name='ФИО автора')
    biography = models.TextField(null=True, blank=True, verbose_name='краткая биография')
    photo = models.ImageField(upload_to='image/%Y/%m/%d',
                              validators=[FileExtensionValidator(['png', 'jpg', 'jpeg'])],
                              null=True, blank=True, verbose_name='Портрет автора')
    birth_date = models.DateField(verbose_name='Дата рождения')
    death_date = models.DateField(null=True, blank=True, verbose_name='Дата смерти')

    def __str__(self):
        return self.full_name

    # определяем метод, которым выстраиваем ссылку для подробной информации об авторе и передаем ее в шаблон
    def get_absolute_url(self):
        return reverse('detail_author', kwargs={'author_id': self.pk})

    class Meta:
        verbose_name = 'Автор книги'
        verbose_name_plural = 'Авторы книг'
        ordering = ['full_name']



library/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from .models import Book, Reviews, Author

'''Формы для отправки данных'''


# форма создания книги
class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'owner', 'description', 'num_pages', 'cover_type', 'price', 'pub_date', 'sizes',
                  'photo_cover', 'photo_back', 'genres']

        widgets = {
            'title': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': '*поле обязательно для заполнения'}),
            'owner': forms.Select(
                attrs={'class': 'form-control', 'placeholder': '*поле обязательно для заполнения'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'num_pages': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': '*поле обязательно для заполнения'}),
            'cover_type': forms.Select(attrs={'class': 'form-control'}),
            'price': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': '*поле обязательно для заполнения'}),
            'pub_date': forms.Select(attrs={'class': 'form-control'}),
            'sizes': forms.TextInput(attrs={'class': 'form-control'}),
            'photo_cover': forms.FileInput(attrs={'class': 'form-control'}),
            'photo_back': forms.FileInput(attrs={'class': 'form-control'}),
            'genres': forms.SelectMultiple(attrs={'class': 'form-control'})
        }


# форма создания Автора книги
class AuthorCreateForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['full_name', 'biography', 'photo', 'birth_date', 'death_date']

        widgets = {
            'full_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': '*поле обязательно для заполнения'}),
            'biography': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
            'birth_date': forms.DateInput(
                attrs={"class": "form-control", 'placeholder': '*введите дату в формате "день.месяц.год"'}),
            'death_date': forms.DateInput(
                attrs={"class": "form-control", 'placeholder': '*если автор жив, это поле заполнять не нужно'})
        }


# форма авторизации пользователя
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', max_length=150,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


# форма регистрации пользователя
class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', max_length=150,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control', 'placeholder': 'Имя пользователя'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(label='Введите пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(label='Подтвердите пароль',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


# форма Отзывов о книге
class ReviewsForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['content', 'raiting']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'raiting': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(ReviewsForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = ""


# форма обратной связи
class ContactForm(forms.Form):
    contact = forms.EmailField(label='Email для обратной связи', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email для обратной связи'}))
    subject = forms.CharField(label='Тема сообщения',
                              widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Тема сообщения'}))
    content = forms.CharField(label='Сообщение', widget=forms.Textarea(
        attrs={'class': 'form-control', "rows": 5, 'placeholder': 'Сообщение'}))

library/templates/library/author/author_add.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block header %}
    {% include 'inc/_header.html' %}
{% endblock %}

{% block hero %}
    {% include 'inc/_hero.html' %}
{% endblock %}

{% block content %}
    <!-- ======= Blog section ======= -->
    <section id="blog" class="blog-mf sect-pt4 route">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-box text-center">
                        <p class="subtitle-a">
                            Здесь вы можете добавить автора в наш каталог
                        </p>
                        <div class="line-mf"></div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="form-comments">
                            <div class="title-box-2">
                                <h3 class="title-left">
                                    Форма добавления автора
                                </h3>
                            </div>
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.non_field.errors }}
                                        <div class="form-group">
                                            {{ form.as_p }}
                                        </div>
                                        <button type="submit" class="button button-a button-rouded">Добавить запись</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Blog -->
{% endblock %}



library/templates/library/author/author_delete.html
{% extends 'base.html' %}\
{% load user_tags %}
{% load static %}

{% block title %}
    <title>{{ title }}/{{ author.full_name }}</title>
{% endblock %}

{% block header %}
    {% include 'inc/_header.html' %}
{% endblock %}

{% block hero %}
    {% include 'inc/_hero.html' %}
{% endblock %}

{% block content %}

    <section id="services" class="services-mf pt-5 route">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-box text-center">
                        <p class="subtitle-a">
                            Подтвердите удаление записи
                        </p>
                        <div class="line-mf"></div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="service-box">
                        <div class="service-ico">
                            <span class="ico-circle"><i class="bi bi-trash"></i></span>
                        </div>
                        <div class="service-content">
                            <h2 class="s-title">Удалить запись об авторе</h2>
                            <p class="s-description text-center">
                                Вы уверены что хотите удалить запись?
                            </p>
                        </div>
                        <div>
                            <form method="post">
                                {% csrf_token %}
                                <button type="button" class="btn btn-secondary" value="Previous Page" onClick="javascript:history.go(-1);">Назад</button>
                                <button type="submit" class="btn btn-primary">Удалить</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- End Blog -->
{% endblock %}


library/templates/library/author/author_detail.html
{% extends 'base.html' %}\
{% load user_tags %}
{% load static %}

{% block title %}
    <title>{{ title }}/{{ author.full_name }}</title>
{% endblock %}

{% block header %}
    {% include 'inc/_header.html' %}
{% endblock %}

{% block hero %}
    {% include 'inc/_hero.html' %}
{% endblock %}

{% block content %}
    <section class="blog-wrapper sect-pt4" id="blog">
        <div class="container">
            <div class="row">
                {% include 'inc/_alerts.html' %}
                <div class="col-md-8">
                    <div class="post-box">
                        {% if author.photo %}
                            <div class="post-thumb">
                                <img src="{{ author.photo.url }}" class="img-fluid" alt="">
                            </div>
                        {% else %}
                            <div class="post-thumb о">
                                <img src="{% static 'assets/img/placeholder.jpg' %}" class="img-fluid" alt="">
                            </div>
                        {% endif %}
                        <div class="post-meta">
                            <h1 class="article-title">{{ author.full_name }}</h1>
                            <ul>
                                <li>
                                    <span class="bi bi-calendar-check">  Дата рождения:</span><a> {{ author.birth_date }}</a>
                                </li>
                            </ul>
                            <ul>
                                {% if author.death_date is None %}
                                    <li>
                                        <span class="bi bi-calendar2-x-fill">  </span><a> жив по сей день</a>
                                    </li>
                                {% else %}
                                    <li>
                                        <span class="bi bi-calendar2-x-fill">  Дата смерти:</span><a> {{ author.death_date }}</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                        <div class="article-content">
                            <p>
                                {{ author.biography }}
                            </p>
                            <blockquote class="blockquote">
                                <p class="mb-0">В описании использованы материалы сайта <a
                                        href="https://book24.ru">book24.ru</a></p>
                            </blockquote>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget-sidebar">
                        <h5 class="sidebar-title">Книги</h5>
                        <div class="sidebar-content">
                            <div class="stars">
                                <ul class="list-sidebar">
                                    {% for book in author.book_set.all %}
                                        <li>
                                            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
{#                    {% if request.user.is_superuser or is_employee is True %}#}
{#                        <div class="widget-sidebar widget-tags">#}
{#                            <h5 class="sidebar-title">Дополнительно</h5>#}
{#                            <div>#}
{#                                <span class="bi bi-pencil-square"></span> <a href="{% url 'edit_author' author.pk %}"><span>Редактировать информацию об авторе</span></a>#}
{#                            </div>#}
{#                            <div>#}
{#                                <span class="bi bi-trash"></span> <a href="{% url 'delete_author' author.pk %}"><span>Удалить запись об авторе</span></a>#}
{#                            </div>#}
{#                        </div>#}
{#                    {% endif %}#}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

library/templates/library/author/author_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block header %}
    {% include 'inc/_header.html' %}
{% endblock %}

{% block hero %}
    {% include 'inc/_hero.html' %}
{% endblock %}

{% block content %}
    <!-- ======= Blog section ======= -->
    <section id="blog" class="blog-mf sect-pt4 route">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-box text-center">
                        <p class="subtitle-a">
                            Здесь вы можете отредактировать запись
                        </p>
                        <div class="line-mf"></div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="form-comments">
                            <div class="title-box-2">
                                <h3 class="title-left">
                                    Форма редактирования информации об авторе
                                </h3>
                            </div>
                            <div class="row">
                                <div class="col-md-12 mb-3">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.non_field.errors }}
                                        <div class="form-group">
                                            {{ form.as_p }}
                                        </div>
                                        <button type="submit" class="button button-a button-rouded">Редактировать запись</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Blog -->
{% endblock %}



library/templates/library/author/authors_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block header %}
    {% include 'inc/_header.html' %}
{% endblock %}

{% block hero %}
    {% include 'inc/_hero.html' %}
{% endblock %}

{% block content %}

    <section id="work" class="portfolio-mf sect-pt4 route">
        <div class="container">
            <div class="row">
                {% include 'inc/_alerts.html' %}
                <div class="col-sm-12">
                    <div class="title-box text-center">
                        <p class="subtitle-a">
                            Здесь вы можете ознакомиться с авторами книг
                        </p>
                        <div class="line-mf"></div>
                    </div>
                </div>
            </div>
            <div class="row">

                {% for author in authors %}
                    <div class="col-md-4">
                        <div class="work-box">
                            {% if author.photo %}
                                <a href="{{ author.photo.url }}" data-gallery="portfolioGallery"
                                   class="portfolio-lightbox">
                                    <div class="work-img">
                                        <img src="{{ author.photo.url }}" alt="" class="img-fluid">
                                    </div>
                                </a>
                            {% else %}
                                <a href="{% static 'assets/img/placeholder.jpg' %}" data-gallery="portfolioGallery"
                                   class="portfolio-lightbox">
                                    <div class="work-img">
                                        <img src="{% static 'assets/img/placeholder.jpg' %}" alt="" class="img-fluid">
                                    </div>
                                </a>
                            {% endif %}
                            <div class="work-content">
                                <div class="row">
                                    <div class="col-sm-8">
                                        <h2 class="w-title">{{ author.full_name }}</h2>
                                        <div class="w-more">
                                            <span class="w-date">{{ author.birth_date }}</span> /
                                            {% if author.death_date is None %}
                                                <span class="w-date">жив по сей день</span>
                                            {% else %}
                                                <span class="w-date">{{ author.death_date }}</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="w-like">
                                            <a href="{{ author.get_absolute_url }}"> <span
                                                    class="bi bi-file-earmark-richtext"></span></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section><!-- End Portfolio Section -->
    {% include 'inc/_pagination.html' %}

{% endblock %}

